/**
 * good-life — English, and the source of truth for the other three.
 *
 * Generated by scripts/bank-to-messages.mjs from docs/banks/good-life.json, which
 * is where these sentences were written and critiqued. This file is that bank
 * keyed the way core/stance.ts looks words up, so a prompt has exactly one
 * home. test/i18n/stance-keys.test.ts fails if the two drift.
 *
 * Item bank © the author, all rights reserved. See LICENSE.
 */
export default {
  "title": "A good life",
  "tagline": "Twelve positions on what a life that went well would contain, and four questions only you read.",
  "framework": "Twelve positions and four open questions — nothing scored",
  "sourceNote": "There is no instrument behind this one and there does not need to be. The wellbeing literature — hedonic and eudaimonic accounts, Ryff's six dimensions, self-determination theory's three needs, Seligman's PERMA, the OECD's eleven domains — was read only as a checklist of what a life is usually said to contain, and nothing was taken from any of it; those questionnaires belong to their authors, several of them require written permission, and none of them is reproduced or paraphrased here. One old and public idea is used as a frame rather than as a checklist: that work can be held as a job, a career or a calling. The research questionnaire built on that idea is not used and not paraphrased. The one place research shaped a question rather than a checklist is the last closed block, which asks what you would regret not doing rather than what you would regret doing, following the finding that regrets of inaction outlast regrets of action over a lifetime — replicated since, with weaker effects and not in every study, so read it as a reason for the question's direction rather than as a fact about you. The four questions at the end have no options at all and never leave this device. Nothing on this page is scored, banded, or set against anybody else's answers. What comes back is what you said, in the order of the weight you put on it, which is why the reasons you write are worth more than the options you tick.",

  /* ── the sections ─────────────────────────────────────────────────── */
  "section.work.title": "What the work is for",
  "section.work.note": "Two questions about what the work is for. They come first because work is the least tender subject here, and because the answer changes how everything later about money reads. One answer to the second declines growth altogether, and it counts like any other.",
  "section.money.title": "Money, and where enough is",
  "section.money.note": "Three questions. The first takes up to two answers, because money genuinely serves more than one purpose at once. The second is not about an amount — it asks what would have to be true before you stopped. The third asks how far into your life a risk may reach.",
  "section.place.title": "Where, and who is near",
  "section.place.note": "Where you live and who is near come apart more often than they look: the town can be settled while the people in it are not, or the other way round. The first question asks about distance alone. The second takes two answers, which makes it a choice rather than a list.",
  "section.week.title": "The body and the week",
  "section.week.note": "The first question is about what you are already giving up, not what you intend to — the intention belongs in the weight underneath it. The second looks a year ahead and names the thing you would cut first.",
  "section.keep.title": "What you keep, what you owe",
  "section.keep.note": "The first question here is the hardest, and takes one answer on purpose: allowed everything, everyone keeps everything, and that tells a reader nothing. Health has to stand against the people you live with and against your own hours. The second takes two.",
  "section.later.title": "Looking back from seventy",
  "section.later.note": "One question, and the last one with options. Eleven positions are already stated before you are asked which absence would sting. The last answer — none of these — is a real one here rather than a way out.",
  "section.open.title": "Open space",
  "section.open.note": "Four questions with no options. What you write is not scored, not compared with anybody, never goes into a share link, and never reaches your instruction sheet — it stays on this device. The last one is four words, because every extra word offers a gentler question to answer.",

  /* ── the questions ────────────────────────────────────────────────── */
  "stance.work-purpose.prompt": "What is your work mainly for?",
  "stance.learn-next.prompt": "What do you want to be visibly better at in ten years?",
  "stance.money-for.prompt": "What is money mainly for?",
  "stance.enough-point.prompt": "What has to be true before you stop trying to earn more?",
  "stance.risk-appetite.prompt": "What would you risk for work you actually wanted?",
  "stance.live-where.prompt": "In ten years, where do you want to be living?",
  "stance.who-near.prompt": "Who would you stay here for?",
  "stance.health-effort.prompt": "What are you giving up now to stay healthy?",
  "stance.less-of.prompt": "What do you most want less of next year?",
  "stance.keep-one.prompt": "If you could keep only one of these, which would it be?",
  "stance.owe-others.prompt": "What do you owe people outside your own household?",
  "stance.regret-most.prompt": "At seventy, which of these would you regret not doing?",

  /* ── what may be answered ─────────────────────────────────────────── */
  /* work-purpose */
  "stance.work-purpose.opt.income": "Paying for the life I have outside it",
  "stance.work-purpose.opt.craft": "Getting good at the thing itself",
  "stance.work-purpose.opt.service": "Being useful to specific people",
  "stance.work-purpose.opt.standing": "Position — being taken seriously",
  "stance.work-purpose.opt.structure": "Structure. I do badly with an open week",
  "stance.work-purpose.opt.undecided": "I have not worked that out",
  /* learn-next */
  "stance.learn-next.opt.trade": "The work I already do",
  "stance.learn-next.opt.newskill": "A skill I have not started yet",
  "stance.learn-next.opt.people": "Handling people, especially conflict",
  "stance.learn-next.opt.temper": "Keeping my head when things go wrong",
  "stance.learn-next.opt.nothing": "Nothing. I want to keep what I have and use it",
  "stance.learn-next.opt.unknown": "I do not know yet",
  /* money-for */
  "stance.money-for.opt.safety": "A buffer, so nothing can force my hand",
  "stance.money-for.opt.freedom": "Buying the freedom to say no",
  "stance.money-for.opt.provide": "Providing for people who depend on me",
  "stance.money-for.opt.now": "Spending it now on things I will remember",
  "stance.money-for.opt.give": "Giving it away while I can see where it lands",
  "stance.money-for.opt.undecided": "I have not worked that out",
  /* enough-point */
  "stance.enough-point.opt.number": "A specific amount in the bank",
  "stance.enough-point.opt.nodebt": "No debt of any kind, the house included",
  "stance.enough-point.opt.hours": "When earning more starts costing time I want",
  "stance.enough-point.opt.never": "Nothing. I do not expect to stop",
  "stance.enough-point.opt.already": "Nothing has to change. I have enough now",
  "stance.enough-point.opt.unknown": "I have never set a point",
  /* risk-appetite */
  "stance.risk-appetite.opt.nothing": "Nothing. Stability is what I am protecting",
  "stance.risk-appetite.opt.months": "A few months of savings, no more than that",
  "stance.risk-appetite.opt.savings": "Most of what I have put by",
  "stance.risk-appetite.opt.income": "Years of lower income for the household",
  "stance.risk-appetite.opt.house": "The house and the standard of living in it",
  "stance.risk-appetite.opt.unsure": "I do not know until it is in front of me",
  /* live-where */
  "stance.live-where.opt.here": "Here. This town, possibly this street",
  "stance.live-where.opt.near": "Within an hour of here",
  "stance.live-where.opt.country": "Somewhere else in this country",
  "stance.live-where.opt.abroad": "Another country",
  "stance.live-where.opt.movable": "Nowhere fixed. I want to be able to move",
  "stance.live-where.opt.undecided": "I have not decided",
  /* who-near */
  "stance.who-near.opt.partner": "The person I live with",
  "stance.who-near.opt.children": "Children, mine or ones I help raise",
  "stance.who-near.opt.parents": "My parents, while they need me",
  "stance.who-near.opt.friends": "Old friends who are here",
  "stance.who-near.opt.community": "A group here I turn up for",
  "stance.who-near.opt.nobody": "Nobody. I would go",
  /* health-effort */
  "stance.health-effort.opt.nothing": "Nothing at the moment",
  "stance.health-effort.opt.sleep": "Evenings out, to protect the sleep",
  "stance.health-effort.opt.drink": "Alcohol, or something else I enjoyed",
  "stance.health-effort.opt.training": "Two or three hours a week of training",
  "stance.health-effort.opt.spend": "Money — food, treatment, dentistry",
  "stance.health-effort.opt.checks": "Time — appointments before anything hurts",
  /* less-of */
  "stance.less-of.opt.hours": "Hours worked",
  "stance.less-of.opt.obligations": "Obligations I did not choose",
  "stance.less-of.opt.debt": "Debt and what it makes me accept",
  "stance.less-of.opt.screen": "Time on a screen at home",
  "stance.less-of.opt.noise": "Noise — people, traffic, mess, interruption",
  "stance.less-of.opt.nothing": "Nothing. The shape of the year is right",
  /* keep-one */
  "stance.keep-one.opt.health": "My health",
  "stance.keep-one.opt.people": "The people I live with",
  "stance.keep-one.opt.voice": "Being able to say what I actually think",
  "stance.keep-one.opt.time": "Control over my own hours",
  "stance.keep-one.opt.standard": "The standard of living I have now",
  "stance.keep-one.opt.unknown": "I have not had to find out",
  /* owe-others */
  "stance.owe-others.opt.nothing": "Nothing beyond leaving them alone",
  "stance.owe-others.opt.money": "A fixed share of what I earn",
  "stance.owe-others.opt.time": "Hours — showing up, driving, sitting with people",
  "stance.owe-others.opt.parents": "Care for my parents when it comes to that",
  "stance.owe-others.opt.useful-work": "Work that is useful beyond what it pays me",
  "stance.owe-others.opt.local": "Turning up for the place I live",
  /* regret-most */
  "stance.regret-most.opt.children": "Having children, or having more of them",
  "stance.regret-most.opt.venture": "Starting the thing I kept planning",
  "stance.regret-most.opt.place": "Living somewhere else while I still could",
  "stance.regret-most.opt.mend": "Mending one relationship before it was too late",
  "stance.regret-most.opt.body": "Looking after my body while it still recovered",
  "stance.regret-most.opt.none": "None of these. I do not think that way",

  /* ── the playbook ─────────────────────────────────────────────────── */
  /* this is fine */
  "playbook.ok-harder-not-bigger": "Give me the harder version of the job before you give me the bigger one.",
  "playbook.ok-money-not-title": "Pay me for the extra work rather than promoting me for it.",
  "playbook.ok-name-who-benefits": "Tell me who is actually helped by this and I will do the dull part of it.",
  "playbook.ok-give-me-fixed-hours": "Give me fixed hours and I will be better at everything inside them.",
  "playbook.ok-stop-offering-growth": "Assume I am not looking for a new challenge and stop putting me forward for one.",
  "playbook.ok-put-me-in-hard-talks": "Put me in the difficult conversation on purpose; I am trying to get better at those.",
  "playbook.ok-tell-me-when-i-snapped": "Tell me when I have been short with you, on the day it happens.",
  "playbook.ok-ask-before-buffer": "Ask me before anything comes out of the savings; I will almost always say yes.",
  "playbook.ok-shorter-week-first": "Offer me the shorter week before you offer me the bigger salary.",
  "playbook.ok-book-it-now": "Book the expensive thing now; I would rather pay for it than wait for it.",
  "playbook.ok-ask-me-for-something-specific": "Ask me for money for one specific thing rather than for a cause.",
  "playbook.ok-no-is-not-modesty": "Believe me when I say I do not want the bigger job; it is not modesty.",
  "playbook.ok-price-it-in-hours": "Tell me what the extra money costs in hours before you ask me to decide.",
  "playbook.ok-risk-stops-at-my-savings": "Bring me the risky plan while the downside stops at my own savings.",
  "playbook.ok-safe-version-first": "Bring me the safe version of the plan first and I will listen properly.",
  "playbook.ok-ask-me-to-move": "Ask me to move for something worth moving for; I am not attached to this address.",
  "playbook.ok-find-the-version-that-stays": "Look for the version of this that does not need me to leave.",
  "playbook.ok-bring-me-the-other-city": "Bring me the job in another city; there is nobody keeping me here.",
  "playbook.ok-dates-early-for-parents": "Give me the dates early; I plan the weekends around my parents.",
  "playbook.ok-early-not-late": "Book me first thing in the morning rather than late at night.",
  "playbook.ok-either-side-of-lunch": "Put the meeting either side of lunch; the middle of the day is training.",
  "playbook.ok-cut-something": "Take something off my list; I would rather do fewer things properly.",
  "playbook.ok-ask-before-my-name": "Ask me before you put my name on anything, even something small.",
  "playbook.ok-ask-what-i-think": "Ask me what I actually think while the decision is still open.",
  "playbook.ok-deadline-not-hours": "Give me the deadline and leave the hours to me.",
  "playbook.ok-call-me-to-show-up": "Call me when somebody needs driving, collecting, or sitting with.",
  "playbook.ok-tell-me-the-street-needs-it": "Tell me when the street needs something done and I will turn up for it.",
  "playbook.ok-tell-me-about-the-opening": "Tell me if you hear of something worth leaving this job for.",
  "playbook.ok-say-if-i-have-gone-quiet": "If I have gone quiet with someone, say so; I would rather be told.",
  "playbook.ok-leave-me-out-of-the-thread": "Leave me out of the group thread for a week and read nothing into it.",
  /* this is not */
  "playbook.not-reassign-my-work": "Do not hand my piece to somebody faster because the date moved.",
  "playbook.not-title-instead-of-money": "Do not offer me a title instead of money and expect it to land as a reward.",
  "playbook.not-remove-the-hours": "Do not take away my fixed hours and call it flexibility.",
  "playbook.not-unasked-development": "Do not enrol me in training I did not ask for.",
  "playbook.not-spend-the-buffer": "Do not spend the emergency money on something that is not an emergency.",
  "playbook.not-assume-my-income": "Do not make plans that assume my income and tell me about them afterwards.",
  "playbook.not-tell-me-i-have-enough": "Do not tell me I have enough; that judgement is mine to make.",
  "playbook.not-laugh-at-the-target": "Do not treat the number I am saving towards as a joke.",
  "playbook.not-stake-what-i-depend-on": "Do not put anything I depend on into a plan I did not agree to.",
  "playbook.not-talk-me-out-of-it": "Do not talk me down from a risk I have already decided to take.",
  "playbook.not-assume-i-will-move": "Do not treat moving away as the obvious answer when the job changes.",
  "playbook.not-assume-i-will-stay": "Do not assume I will still be living here in five years.",
  "playbook.not-book-my-parent-weekends": "Do not book the weekend without asking whether I am needed at my parents'.",
  "playbook.not-two-weekends-running": "Do not ask me to work two weekends in a row; I am already counting them.",
  "playbook.not-press-the-drink": "Do not offer me a drink again after I have said no once.",
  "playbook.not-joke-about-checkups": "Do not make a joke of the appointments; going early is not hypochondria.",
  "playbook.not-volunteer-me": "Do not put my name down for something and tell me afterwards.",
  "playbook.not-message-me-late": "Do not send me work messages after nine and expect an answer.",
  "playbook.not-fill-my-calendar": "Do not fill my week and then ask why I am short with people.",
  "playbook.not-every-evening-out": "Do not put something in every evening; I want to be in the house.",
  "playbook.not-sign-me-up-locally": "Do not sign me up for the collection, the committee, or the street party.",
  "playbook.not-joke-about-children": "Do not make jokes about whether I am going to have children.",
  "playbook.not-ring-me": "Do not ring me when a message would have done.",

  /* ── open space ───────────────────────────────────────────────────── */
  "item.open-letter": "A letter to yourself at seventy. What should be true?",
  "item.open-five": "What one thing would make the next five years count?",
  "item.open-said": "What would you want the people who knew you best to say?",
  "item.open-avoid": "What are you avoiding?",

  /* ── the instruction sheet ─────────────────────────────────────
     Six headings, on the four channels the spec declares. Not the six
     sections: those are the order the questions are asked in, and a card is
     what somebody reads off a printed sheet weeks later. Every body under
     these is the reader's own chosen words and nothing composed for them, and
     the four open questions produce no card at all — the sheet is the thing
     you hand over, and «What are you avoiding?» is not. */
  "card.work": "What the work is for",
  "card.money": "Money, and where I stop",
  "card.health": "What I give up to stay healthy",
  "card.less": "What I want less of",
  "card.place": "Where I want to be, and who I would stay for",
  "card.keep": "What I would keep, owe, and regret",

  /* ── the result page ───────────────────────────────────────────
     Two weight lists and the sentence over them, then the one paragraph this
     instrument owes that no other does: what was not done with the four
     answers nobody else will ever see. The headings are statements about the
     reader's own numbers and never a verdict on the life behind them. */
  "view.weightTitle": "Where the weight fell",
  "view.weightNote": "The two ends of the numbers you gave. Anything you put between four and seven is not missing — it is above, in the order you were asked.",
  "view.heaviestTitle": "What you weighted heaviest",
  "view.heaviestNote": "Eight or more out of ten. These are the ones where being wrong about you costs the most.",
  "view.lightestTitle": "What you weighted lightest",
  "view.lightestNote": "Three or less out of ten. There is room to move here, which is not the same as not minding.",
  "view.openNote": "These four are yours. Nothing here was scored, nothing was set against anybody else's answers, and none of it goes into a link — it is on this page because you wrote it.",
};
