/**
 * Every instrument, in catalogue order.
 *
 * Generated by scripts/write-registry.mjs. Static imports rather than a glob:
 * the list is the manifest, a missing entry shows up as a diff, and the
 * bundler can see the whole graph. Message tables stay lazy — they are the
 * large part — so adding a locale costs nothing at the entry point.
 */
import { createRegistry, type InstrumentModule } from "@/core/registry";

import loveLanguages from "./love-languages";
import attachment from "./attachment";
import coupleConversations from "./couple-conversations";
import intimacyConditions from "./intimacy-conditions";
import attraction from "./attraction";
import conflictStyle from "./conflict-style";
import enneagram from "./enneagram";
import bigFive from "./big-five";
import hexaco from "./hexaco";
import jungian from "./jungian";
import riasec from "./riasec";
import workingStyle from "./working-style";
import studyPractice from "./study-practice";
import chronotype from "./chronotype";

const MODULES = [
  loveLanguages,
  attachment,
  coupleConversations,
  intimacyConditions,
  attraction,
  conflictStyle,
  enneagram,
  bigFive,
  hexaco,
  jungian,
  riasec,
  workingStyle,
  studyPractice,
  chronotype,
] as unknown as InstrumentModule[];

export const registry = createRegistry(MODULES);
export default registry;
