/**
 * One dynamic import per instrument, written out as literals.
 *
 * Generated by scripts/write-registry.mjs.
 *
 * The runner and the result page both need an instrument's own code — score()
 * to compute a reading, View to draw it — and both are client routes, because
 * a result lives in local storage and never reaches a server. Importing the
 * registry there would put every instrument in the bundle of whichever one the
 * reader opened. A map of literal import() calls is what lets the bundler
 * split them; a computed specifier resolves at runtime but leaves the graph
 * unknowable, so the bundler either ships everything or nothing.
 */
import type { InstrumentModule } from "@/core/registry";

type Loader = () => Promise<{ default: InstrumentModule }>;

const LOADERS: Record<string, Loader> = {
  "love-languages": () => import("./love-languages") as Promise<{ default: InstrumentModule }>,
  "attachment": () => import("./attachment") as Promise<{ default: InstrumentModule }>,
  "couple-conversations": () => import("./couple-conversations") as Promise<{ default: InstrumentModule }>,
  "intimacy-conditions": () => import("./intimacy-conditions") as Promise<{ default: InstrumentModule }>,
  "attraction": () => import("./attraction") as Promise<{ default: InstrumentModule }>,
  "conflict-style": () => import("./conflict-style") as Promise<{ default: InstrumentModule }>,
  "enneagram": () => import("./enneagram") as Promise<{ default: InstrumentModule }>,
  "big-five": () => import("./big-five") as Promise<{ default: InstrumentModule }>,
  "hexaco": () => import("./hexaco") as Promise<{ default: InstrumentModule }>,
  "jungian": () => import("./jungian") as Promise<{ default: InstrumentModule }>,
  "riasec": () => import("./riasec") as Promise<{ default: InstrumentModule }>,
  "working-style": () => import("./working-style") as Promise<{ default: InstrumentModule }>,
  "study-practice": () => import("./study-practice") as Promise<{ default: InstrumentModule }>,
  "chronotype": () => import("./chronotype") as Promise<{ default: InstrumentModule }>,
};

export const hasInstrument = (id: string) => id in LOADERS;

export async function loadInstrumentModule(id: string): Promise<InstrumentModule | null> {
  const loader = LOADERS[id];
  if (!loader) return null;
  return (await loader()).default;
}
