/**
 * faith — English, and the source of truth for the other three.
 *
 * Generated by scripts/bank-to-messages.mjs from docs/banks/faith.json, which
 * is where these sentences were written and critiqued. This file is that bank
 * keyed the way core/stance.ts looks words up, so a prompt has exactly one
 * home. test/i18n/stance-keys.test.ts fails if the two drift.
 *
 * Item bank © the author, all rights reserved. See LICENSE.
 */
export default {
  "title": "Faith",
  "tagline": "Twelve positions on what you hold, what weight you put on each, and what it rests on.",
  "framework": "Twelve stated positions — nothing graded, nothing scored",
  "sourceNote": "There is no validated instrument behind this one and none is wanted. Religiosity research supplied a map of the subject area and nothing else: Glock's five dimensions of 1962 (belief, practice, experience, knowledge, consequences), Davie's observation in 1994 that believing and belonging come apart, and Huber and Huber's centrality construct of 2012 are why these twelve blocks are grouped into what is held, what is practised, where it came from and what it touches. The Centrality of Religiosity Scale, the Duke University Religion Index, Allport and Ross's Religious Orientation Scale, the Religious Commitment Inventory-10, the Santa Clara Strength of Religious Faith Questionnaire and the Fetzer/NIA measure were all read; none of their items appear here. Reading them is also why two questions an earlier draft carried are not here. An attendance-frequency ladder is the shape of DUREL's first item and of the CRS public-practice item, so this instrument asks where you belong instead of how often you go. A \"what settles right and wrong\" item is the shape of a Pew question, and it duplicated the grounds vocabulary that already runs under every block, so it was cut rather than reworded. Nothing is scored. There is no devoutness figure and no orthodoxy figure, and there is no reliability coefficient or factor structure either, because a position you state has none and needs none — you are not being placed against a sample, you are writing down what you hold and what you think it rests on. Every block that assumes a belief carries an option declining the assumption, so the form runs straight through for someone who holds a faith firmly, for someone who has left one and for someone who never had one, and none of those three is treated as the incomplete answer. No block asks about anyone but you: there is no question here that a person answering alone has to invent a partner in order to reach.",

  /* ── the sections ─────────────────────────────────────────────────── */
  "section.belief.title": "What is held",
  "section.belief.note": "God, death, and suffering. There is no orthodox answer on this page and nothing on it is graded.",
  "section.practice.title": "Practice and belonging",
  "section.practice.note": "One question asks when you last did it. The other asks where you belong. Neither is added to the other, and neither is a measure of devoutness.",
  "section.lineage.title": "Where it came from, where it goes",
  "section.lineage.note": "The distance between how you were raised and where you now stand, what you would want passed on, and what should happen on the day you cannot say.",
  "section.consequences.title": "What it touches",
  "section.consequences.note": "Money and time. A belief either shows up in a bank statement and a calendar or it does not, which is a fact about a household rather than about a soul.",
  "section.edges.title": "The edges",
  "section.edges.note": "What has no give in it, and what is still open. A person holding this sheet needs the second list as much as the first.",

  /* ── the questions ────────────────────────────────────────────────── */
  "stance.god.prompt": "What is God to you?",
  "stance.after-death.prompt": "What do you think happens after you die?",
  "stance.suffering.prompt": "Why do you think suffering happens?",
  "stance.prayer-last.prompt": "When did you last pray on your own?",
  "stance.belonging.prompt": "Where do you belong in what you believe?",
  "stance.raised-vs-now.prompt": "What changed between how you were raised and now?",
  "stance.children-taught.prompt": "What should a child in your care be taught about faith?",
  "stance.funeral.prompt": "What should happen at your own funeral?",
  "stance.money-use.prompt": "Where does your belief show up in your money?",
  "stance.work-rest.prompt": "Is there a time your belief keeps clear of work?",
  "stance.non-negotiable.prompt": "In faith, what would you refuse to give up?",
  "stance.unsettled.prompt": "Which of these are you genuinely unsure about?",

  /* ── what may be answered ─────────────────────────────────────────── */
  /* god */
  "stance.god.opt.close": "Someone I can speak to and be heard by",
  "stance.god.opt.distant": "Someone real, whom I do not feel close to",
  "stance.god.opt.impersonal": "A word for something I cannot name",
  "stance.god.opt.untrue": "An idea I do not think is true",
  "stance.god.opt.open": "A question I have left open",
  "stance.god.opt.rather-not": "I would rather not say",
  /* after-death */
  "stance.after-death.opt.life-with-god": "Life continuing in God's presence",
  "stance.after-death.opt.another-life": "Another life, lived again",
  "stance.after-death.opt.something": "Something continues, though I could not say what",
  "stance.after-death.opt.nothing": "Nothing continues",
  "stance.after-death.opt.not-worked-out": "I have not worked out what I think",
  "stance.after-death.opt.rather-not": "I would rather not say",
  /* suffering */
  "stance.suffering.opt.reason-i-trust": "It is allowed for a reason I trust",
  "stance.suffering.opt.reason-unknown": "It is allowed, and I do not know why",
  "stance.suffering.opt.no-one-allows": "Nobody allows it — it simply happens",
  "stance.suffering.opt.people-do-it": "It is what people do to each other",
  "stance.suffering.opt.not-worked-out": "I have not worked out what I think",
  "stance.suffering.opt.rather-not": "I would rather not say",
  /* prayer-last */
  "stance.prayer-last.opt.today": "Today",
  "stance.prayer-last.opt.this-week": "In the last week",
  "stance.prayer-last.opt.this-year": "In the last year",
  "stance.prayer-last.opt.longer-ago": "Longer ago than that",
  "stance.prayer-last.opt.never": "Never, as far as I know",
  /* belonging */
  "stance.belonging.opt.known-by-name": "A congregation that knows me by name",
  "stance.belonging.opt.a-face": "A congregation where I am a face, not a name",
  "stance.belonging.opt.people-not-institution": "People I practise with, outside any institution",
  "stance.belonging.opt.tradition-only": "A tradition, but no group of people",
  "stance.belonging.opt.nowhere-content": "Nowhere, by choice",
  "stance.belonging.opt.nowhere-missed": "Nowhere, though I would like to",
  /* raised-vs-now */
  "stance.raised-vs-now.opt.stayed": "Nothing — I hold what I was raised in",
  "stance.raised-vs-now.opt.stayed-differently": "The same faith, held differently from how I was taught",
  "stance.raised-vs-now.opt.left": "I have left it and hold no faith now",
  "stance.raised-vs-now.opt.found": "I hold a faith I was not raised in",
  "stance.raised-vs-now.opt.none-either-way": "No faith then, none now",
  "stance.raised-vs-now.opt.still-moving": "I am still moving",
  /* children-taught */
  "stance.children-taught.opt.raised-in-it": "Raised in my faith by default",
  "stance.children-taught.opt.taught-then-choose": "Taught my faith, then free to choose",
  "stance.children-taught.opt.several": "Taught about several faiths, none of them privileged",
  "stance.children-taught.opt.none-unless-asked": "Nothing religious unless they ask",
  "stance.children-taught.opt.undecided": "I have not decided",
  /* funeral */
  "stance.funeral.opt.full-rite": "The rite of my faith, in full",
  "stance.funeral.opt.simple-rite": "A religious service, kept short",
  "stance.funeral.opt.words-not-religious": "Words said over me, none of them religious",
  "stance.funeral.opt.nothing-religious": "Nothing religious of any kind",
  "stance.funeral.opt.whatever-comforts": "Whatever comforts the people who are there",
  "stance.funeral.opt.undecided": "I have not decided",
  /* money-use */
  "stance.money-use.opt.fixed-share": "A fixed share of income is given away",
  "stance.money-use.opt.give-when-asked": "I give when I am asked, with no fixed share",
  "stance.money-use.opt.wont-earn": "There is money I will not earn",
  "stance.money-use.opt.wont-spend": "There is money I will not spend",
  "stance.money-use.opt.touches-nothing": "It touches none of my money",
  "stance.money-use.opt.not-thought": "I have not thought about it",
  /* work-rest */
  "stance.work-rest.opt.whole-day": "Yes, a whole day I keep clear",
  "stance.work-rest.opt.part-day": "Yes, part of a day",
  "stance.work-rest.opt.in-principle": "In principle, though I do not manage it",
  "stance.work-rest.opt.no-but-rest": "No, though I rest for other reasons",
  "stance.work-rest.opt.no": "No",
  /* non-negotiable */
  "stance.non-negotiable.opt.children": "How children in my care are raised",
  "stance.non-negotiable.opt.practice": "Practising, even where it is unwelcome",
  "stance.non-negotiable.opt.saying-so": "Saying what I believe when I am asked",
  "stance.non-negotiable.opt.belonging": "Staying part of the people I gather with",
  "stance.non-negotiable.opt.left-alone": "Being left alone about it",
  "stance.non-negotiable.opt.nothing": "Nothing here is beyond discussion",
  /* unsettled */
  "stance.unsettled.opt.god-exists": "Whether there is a God at all",
  "stance.unsettled.opt.after-death": "What happens after death",
  "stance.unsettled.opt.suffering": "Why suffering is allowed",
  "stance.unsettled.opt.tradition-right": "Whether the tradition I came from has it right",
  "stance.unsettled.opt.own-honesty": "Whether I believe it or only keep the habit",
  "stance.unsettled.opt.nothing-unsure": "None of these are open for me",

  /* ── what a position rests on ─────────────────────────────────────── */
  "stance.god.groundsPrompt": "What does what you hold about God rest on?",
  "stance.after-death.groundsPrompt": "What does that answer about death rest on?",
  "stance.suffering.groundsPrompt": "What does that answer about suffering rest on?",
  "stance.prayer-last.groundsPrompt": "What does your practice of prayer rest on?",
  "stance.belonging.groundsPrompt": "What does where you belong rest on?",
  "stance.raised-vs-now.groundsPrompt": "What does where you now stand rest on?",
  "stance.children-taught.groundsPrompt": "What does that answer about a child rest on?",
  "stance.funeral.groundsPrompt": "What does that answer about your funeral rest on?",
  "stance.money-use.groundsPrompt": "What does that answer about your money rest on?",
  "stance.work-rest.groundsPrompt": "What does that answer about your time rest on?",
  "stance.non-negotiable.groundsPrompt": "What does that refusal rest on?",
  "stance.unsettled.groundsPrompt": "What does that uncertainty rest on?",
  "stance.grounds.scripture": "Scripture",
  "stance.grounds.church": "The teaching of my church",
  "stance.grounds.reason": "Reason and argument",
  "stance.grounds.experience": "Something I have lived through",
  "stance.grounds.upbringing": "How I was raised",
  "stance.grounds.people": "People I trust",
  "stance.grounds.not-worked-out": "I have not worked that out",

  /* ── the playbook ─────────────────────────────────────────────────── */
  /* this is fine */
  "playbook.ok-call-me-on-the-day": "You can call me on the day I keep clear if something is actually wrong. I would rather be called.",
  "playbook.ok-pray-around-me": "You can carry on talking and moving around me while I pray. It does not need the room to go quiet.",
  "playbook.ok-ask-me-straight": "You can ask me outright whether I believe it. You will get a plain answer and it will not be a long one.",
  "playbook.ok-say-i-dont-look-it": "You can say that I do not look like someone who believes this. I know how it looks. It is still true.",
  "playbook.ok-say-grace": "You can say grace at your own table with me sitting there. I will be quiet and it costs me nothing.",
  "playbook.ok-invite-me-anyway": "You can invite me to a service for your wedding or your child's baptism and I will come.",
  "playbook.ok-ask-me-along": "You can ask me to come with you. Asking a second time is fine; I am not avoiding it on purpose.",
  "playbook.ok-name-the-old-parish": "You can mention the church I grew up in without lowering your voice. It is not a wound.",
  "playbook.ok-answer-my-kids-honestly": "You can answer my children's questions about what you believe honestly, including where you disagree with me.",
  "playbook.ok-take-them-along": "Take a child along to whatever you go to. I want them to have seen it before they are old enough to choose.",
  "playbook.ok-ask-what-i-give": "You can ask me what I give away and who receives it. The number is not a secret.",
  "playbook.ok-call-out-the-slip": "You can point out that I said I would keep the time clear and then worked straight through it. That is fair.",
  "playbook.ok-plain-speech-about-death": "You can talk about someone dying in front of me without hunting for a form of words. Plain speech is easier for me.",
  "playbook.ok-bring-hard-questions": "You can bring me the hardest question you have about suffering. I am not going to defend anything.",
  "playbook.ok-ask-in-public": "You can ask me what I believe in front of other people. I would rather answer than be protected from it.",
  /* this is not */
  "playbook.no-small-work-messages": "Do not send me work messages on the day I keep clear, not even the short ones.",
  "playbook.no-phase-talk": "Do not describe my praying as a mood I am in or a phase I am going through.",
  "playbook.no-praying-over-me": "Do not pray over me without asking me first.",
  "playbook.no-treating-it-as-taste": "Do not treat what I hold as a preference of mine rather than a claim I think is actually true.",
  "playbook.no-fixing-the-distance": "Do not treat the distance I feel from God as a problem for you to solve for me.",
  "playbook.no-you-will-return": "Do not tell me I will come back to it when I am older. I have heard it, and it lands as contempt.",
  "playbook.no-unexamined-assumption": "Do not assume I have never examined this just because I was raised in it.",
  "playbook.no-service-detour": "Do not take my children into another faith's service without asking me first.",
  "playbook.notok-baptism-without-me": "Do not have a child baptised or dedicated without me in the room.",
  "playbook.no-filling-in-my-view": "Do not tell people what I think happens after death when somebody has died. I have not settled it.",
  "playbook.no-supplying-the-reason": "Do not hand me a reason for what happened. I hold that there is one and that I do not get to know it.",
  "playbook.no-raiding-the-giving": "Do not treat what I give away as money that was available for something else.",
  "playbook.no-improvising-the-funeral": "Do not improvise at my funeral. The rite is written down and I want it followed as written.",
  "playbook.no-doubt-as-ammunition": "Do not bring up my doubts in an argument that is about something else.",
  "playbook.no-deciding-without-me": "Do not settle anything about how my children are raised in faith while I am not in the room.",

  /* ── hand-written — not from the bank, carried through untouched ──── */
  "card.holds": "What I hold, and what it rests on",
  "card.belong": "Where I belong",
  "card.passed-on": "Children, my funeral, and my money",
  "card.kept-clear": "The time my belief keeps clear",
  "card.no-give": "What I will not give up",
  "card.still-open": "What I have not settled",
  "view.rests": "Rests on:",
  "view.heaviest.title": "What you weighted heaviest",
  "view.heaviest.note": "The questions you put the most weight on. Nothing is added up here and nothing is compared with anyone — it is where you said there is least give, which is what somebody reading this needs before they walk into one of them.",
  "view.lightest.title": "What you weighted lightest",
  "view.lightest.note": "Answered, and given the least weight. That is not the same as having no position: it is you saying there is room to move here, and that is worth as much to the person reading this as the list above.",
};
