/**
 * digital-life — English, and the source of truth for the other three.
 *
 * Generated by scripts/bank-to-messages.mjs from docs/banks/digital-life.json, which
 * is where these sentences were written and critiqued. This file is that bank
 * keyed the way core/stance.ts looks words up, so a prompt has exactly one
 * home. test/i18n/stance-keys.test.ts fails if the two drift.
 *
 * Item bank © the author, all rights reserved. See LICENSE.
 */
export default {
  "title": "Digital life",
  "tagline": "Twelve positions about your phone, what gets posted and what is kept, each with its weight.",
  "framework": "Twelve stated positions — nothing scored, nothing inferred",
  "sourceNote": "No validated instrument sits behind this one, because none exists — the questions were written here, and the research was used to choose which ones to ask rather than to say anything about your answers. What that research supports is modest and worth stating at its real size. In a meta-analysis of partner phubbing (Ni and colleagues, Frontiers in Psychology, 2025), the association between feeling phubbed by a partner and relationship satisfaction was r = −0.22 across 30 samples and 9,040 people — real, small, and drawn almost entirely from cross-sectional data that cannot say which way it runs. A dyadic diary study found the effect attaches to the perception rather than to the behaviour: a partner's own reported phone use predicted nothing, while feeling phubbed predicted lower relationship quality on the day — and that day-level effect did not hold two months later either (Carnelley, Vowels, Stanton, Millings and Hart, Computers in Human Behavior 147, 2023). Sharenting is the one subject here where the person most affected is not the one answering: the reviewed harms are documented — a permanent footprint the child did not choose, image misuse, conflict with the grown child over posts they never agreed to — the studies behind them are small and largely descriptive, and in one survey of 1,460 Czech and Spanish parents, around four in five had posted pictures of their child while only about one in five had asked the child first. For group chats, for what should never be typed at all, and for what people want done with their accounts afterwards there is no useful evidence whatever; those questions are here because they get settled by default rather than because anything is known about them. Nothing on this page is scored, inferred, or turned into a number.",

  /* ── the sections ─────────────────────────────────────────────────── */
  "section.attention.title": "Attention",
  "section.attention.note": "What a phone is allowed to interrupt, and how soon an answer is expected.",
  "section.visibility.title": "What other people see",
  "section.visibility.note": "Publication — including the one person in this section who is not here to answer for themselves.",
  "section.access.title": "What is open",
  "section.access.note": "Passwords, locations, and whether an unlocked phone on the table is an invitation.",
  "section.permanence.title": "What is kept",
  "section.permanence.note": "What may exist, what should never be typed at all, and what happens to the whole archive afterwards.",

  /* ── the questions ────────────────────────────────────────────────── */
  "stance.phone-at-meals.prompt": "Where should phones be during a shared meal?",
  "stance.reply-window.prompt": "How soon should a direct question get an answer?",
  "stance.work-after-hours.prompt": "When may work reach you outside working hours?",
  "stance.posted-about-me.prompt": "What may not be posted about you without asking?",
  "stance.children-online.prompt": "What is the most that may be posted about your child?",
  "stance.group-chats.prompt": "What of yours should stay out of a group chat?",
  "stance.passwords.prompt": "Which passwords of yours should someone else have?",
  "stance.location.prompt": "Who may see where you are right now?",
  "stance.reading-messages.prompt": "Who may read the messages on your phone?",
  "stance.intimate-images.prompt": "What may happen to intimate photographs of you?",
  "stance.not-in-writing.prompt": "Which of these should never arrive as a message?",
  "stance.accounts-after-death.prompt": "What should be left of your accounts after you die?",

  /* ── what may be answered ─────────────────────────────────────────── */
  /* phone-at-meals */
  "stance.phone-at-meals.opt.out-of-room": "Out of the room entirely",
  "stance.phone-at-meals.opt.silent-away": "Nearby but silent and out of sight",
  "stance.phone-at-meals.opt.face-down": "On the table, face down, untouched",
  "stance.phone-at-meals.opt.used-freely": "Used freely, like any other time",
  "stance.phone-at-meals.opt.no-rule": "I have no rule about this",
  /* reply-window */
  "stance.reply-window.opt.hours": "Within a few hours",
  "stance.reply-window.opt.same-day": "The same day",
  "stance.reply-window.opt.day-or-more": "A day or more is fine",
  "stance.reply-window.opt.urgent-only": "Only if I said it was urgent",
  "stance.reply-window.opt.never": "There is no expectation at all",
  "stance.reply-window.opt.undecided": "I have not thought about it",
  /* work-after-hours */
  "stance.work-after-hours.opt.never": "Never, it waits until morning",
  "stance.work-after-hours.opt.cannot-wait": "Only for something that cannot wait",
  "stance.work-after-hours.opt.any-evening": "Any evening, until I go to sleep",
  "stance.work-after-hours.opt.any-time": "Any time at all",
  "stance.work-after-hours.opt.no-work": "My work has no way to reach me",
  "stance.work-after-hours.opt.undecided": "I have not decided this",
  /* posted-about-me */
  "stance.posted-about-me.opt.photos": "A photograph I appear in",
  "stance.posted-about-me.opt.full-name": "My full name, written out",
  "stance.posted-about-me.opt.whereabouts": "Where I am at the time",
  "stance.posted-about-me.opt.relationship": "News about my relationship",
  "stance.posted-about-me.opt.none": "None of these — post any of it freely",
  /* children-online */
  "stance.children-online.opt.nothing": "Nothing at all, ever",
  "stance.children-online.opt.private-only": "Only sent privately to people I choose",
  "stance.children-online.opt.closed-account": "On a closed account, never a public one",
  "stance.children-online.opt.public-no-identifiers": "Publicly, with no face and no name",
  "stance.children-online.opt.public-open": "Publicly, like anything else",
  "stance.children-online.opt.undecided": "I have not settled this",
  /* group-chats */
  "stance.group-chats.opt.screenshots": "Screenshots of my messages",
  "stance.group-chats.opt.arguments": "An argument we had",
  "stance.group-chats.opt.health": "Anything about my health",
  "stance.group-chats.opt.money": "Anything about my money",
  "stance.group-chats.opt.none": "None of these — repeat any of it",
  /* passwords */
  "stance.passwords.opt.none": "None of them",
  "stance.passwords.opt.shared-accounts": "Only accounts we both already use",
  "stance.passwords.opt.shared-plus-passcode": "Those, plus my phone passcode",
  "stance.passwords.opt.emergency-all": "All of them, kept for an emergency",
  "stance.passwords.opt.all-any-time": "All of them, to use any time",
  "stance.passwords.opt.undecided": "I have not decided this",
  /* location */
  "stance.location.opt.nobody": "Nobody, ever",
  "stance.location.opt.only-when-i-send": "Only when I send it myself",
  "stance.location.opt.travelling": "One person, while I travel or am out late",
  "stance.location.opt.one-person-always": "One person, always on",
  "stance.location.opt.household-always": "My whole household, always on",
  "stance.location.opt.undecided": "I have not decided this",
  /* reading-messages */
  "stance.reading-messages.opt.nobody": "Nobody, not even in an emergency",
  "stance.reading-messages.opt.if-incapable": "Only if I cannot answer for myself",
  "stance.reading-messages.opt.handed-over": "Only what I have handed over to show",
  "stance.reading-messages.opt.ask-first": "One person, if they ask me first",
  "stance.reading-messages.opt.one-person-anytime": "One person, any time, without asking",
  "stance.reading-messages.opt.undecided": "I have not decided this",
  /* intimate-images */
  "stance.intimate-images.opt.none": "None should exist at all",
  "stance.intimate-images.opt.deleted": "Taken, then deleted the same day",
  "stance.intimate-images.opt.my-device": "Only on a device I control",
  "stance.intimate-images.opt.no-cloud": "On either person's device, never a cloud",
  "stance.intimate-images.opt.anywhere": "Anywhere, cloud backups included",
  "stance.intimate-images.opt.rather-not": "I would rather not answer this",
  /* not-in-writing */
  "stance.not-in-writing.opt.apology": "An apology that matters",
  "stance.not-in-writing.opt.end-of-argument": "The end of an argument",
  "stance.not-in-writing.opt.health-news": "Bad news about someone's health",
  "stance.not-in-writing.opt.money-decision": "A decision about money",
  "stance.not-in-writing.opt.criticism": "Anything critical of me",
  "stance.not-in-writing.opt.none": "None of these — a message is fine",
  /* accounts-after-death */
  "stance.accounts-after-death.opt.nothing": "Nothing — delete all of it",
  "stance.accounts-after-death.opt.photographs": "The photographs only",
  "stance.accounts-after-death.opt.no-messages": "Everything except my private messages",
  "stance.accounts-after-death.opt.as-it-is": "Everything, exactly as it is",
  "stance.accounts-after-death.opt.undecided": "I have not thought about it",

  /* ── what a position rests on ─────────────────────────────────────── */
  "stance.work-after-hours.groundsPrompt": "Where does that rule about work in the evening come from?",
  "stance.children-online.groundsPrompt": "Where does that limit on your child's photographs come from?",
  "stance.location.groundsPrompt": "Where does that view of sharing your location come from?",
  "stance.reading-messages.groundsPrompt": "Where does that line around your messages come from?",
  "stance.intimate-images.groundsPrompt": "Where does that answer about those photographs come from?",
  "stance.grounds.safety": "Safety, mine or somebody else's",
  "stance.grounds.consent": "Somebody else has not agreed to it",
  "stance.grounds.experience": "Something that happened to me before",
  "stance.grounds.privacy": "Wanting part of my life to stay mine",
  "stance.grounds.trust": "What trust looks like to me",
  "stance.grounds.obligation": "My work or the law requires it",
  "stance.grounds.not-worked-out": "I have not worked that out",

  /* ── the playbook ─────────────────────────────────────────────────── */
  /* this is fine */
  "playbook.ok-phone-in-another-room": "Leave your phone in another room while we eat, without announcing it — I will not read that as a sulk.",
  "playbook.ok-glance-if-you-say-so": "Glance at your phone at the table if you are waiting on something — just tell me you are.",
  "playbook.ok-phone-out-at-dinner": "Use your phone at the table without checking my face first — I genuinely do not mind.",
  "playbook.ok-one-line-holds-it": "Send me one line saying you cannot answer properly yet; that counts as an answer.",
  "playbook.ok-reply-tomorrow": "Leave my message until tomorrow if you are tired; I have not been counting the hours.",
  "playbook.ok-silence-costs-nothing": "Take as long as you want to reply, and do not open with an apology for the gap.",
  "playbook.ok-send-what-cannot-wait": "Message me after hours if it genuinely will not keep until the morning.",
  "playbook.ok-take-the-work-call": "Take the work call in the evening, as long as you tell me it is work.",
  "playbook.ok-post-me-unasked": "Post the photograph of me if you like it — you do not need to check with me first.",
  "playbook.ok-send-child-photos-privately": "Send photographs of our child straight to the people who want them rather than posting them anywhere.",
  "playbook.ok-ask-the-child": "Show our child the photograph before it goes up, and take a no for an answer without arguing them out of it.",
  "playbook.ok-tell-your-friends": "Tell your friends we argued if it helps you — I would rather you had someone to talk to than carried it.",
  "playbook.ok-use-shared-logins": "Log into the accounts we both use without asking me each time.",
  "playbook.ok-use-my-passcode": "Use my passcode if you cannot reach me and something actually needs doing.",
  "playbook.ok-location-when-travelling": "Turn my location on while I am travelling, and turn it off again when I am home.",
  "playbook.ok-check-my-location": "Look at my location whenever you want — that is what I turned it on for.",
  "playbook.ok-open-my-phone-if-i-cannot": "Get into my phone if I am in hospital and cannot answer it myself.",
  "playbook.ok-read-the-handed-phone": "Read anything on my phone once I have handed it to you — I do not need to watch you do it.",
  "playbook.ok-delete-on-request": "Ask me to delete a photograph of you and expect it gone the same day, with no discussion attached.",
  "playbook.ok-call-instead-of-typing": "Call me rather than typing it if the thing you have to say is bad news about someone's health.",
  "playbook.ok-message-is-fine": "Send it as a message if that is easier; none of it has to be said out loud.",
  "playbook.ok-name-me-legacy-contact": "Name me as your legacy contact on your phone and your email, so nobody has to argue with a helpline later.",
  /* this is not */
  "playbook.no-phone-at-the-table": "Do not bring your phone to the table at all — not face down, not on silent.",
  "playbook.no-scroll-mid-sentence": "Do not start scrolling while I am halfway through a sentence, even if you are still listening.",
  "playbook.no-day-long-silence": "Do not leave a direct question unanswered all day without one line about why.",
  "playbook.no-work-in-the-evening": "Do not answer a work message in the evening; it will still be there in the morning.",
  "playbook.no-work-unless-it-burns": "Do not send me work after hours unless you would have phoned me about it.",
  "playbook.no-post-me-unasked": "Do not post a photograph I am in without asking me first, including in a story that disappears.",
  "playbook.no-name-me-in-public": "Do not write my full name in a public post, even in a thank-you.",
  "playbook.no-post-where-i-am": "Do not post where I am while I am still there.",
  "playbook.no-announce-my-relationship": "Do not announce anything about my relationship before I have.",
  "playbook.no-child-at-all": "Do not post about our child anywhere, including to people you would trust with them.",
  "playbook.no-child-face-public": "Do not put our child's face on a public account — not once, not even a good photograph.",
  "playbook.no-child-school-or-uniform": "Do not post anything that names our child's school or shows their uniform.",
  "playbook.no-child-embarrassment": "Do not post our child crying or being told off, even as a joke about parenting.",
  "playbook.no-screenshot-into-group": "Do not screenshot my messages into a group chat, however good the line was.",
  "playbook.no-argument-into-group": "Do not tell the group chat about an argument we are still in the middle of.",
  "playbook.no-health-into-group": "Do not pass on anything about my health, even to people who would only worry kindly.",
  "playbook.no-money-into-group": "Do not repeat what I earn or what I owe to anybody, in any chat.",
  "playbook.no-shared-logins-in-my-name": "Do not set up an account in my name and keep the password yourself.",
  "playbook.no-check-instead-of-asking": "Do not check my location to find out where I am instead of asking me where I am.",
  "playbook.no-read-while-i-shower": "Do not read my messages while I am in the shower, even though the phone is sitting there unlocked.",
  "playbook.no-intimate-photos-at-all": "Do not take intimate photographs of me at all, however safely you would keep them.",
  "playbook.no-cloud-backup-of-photos": "Do not keep intimate photographs of me in anything that syncs to a cloud.",
  "playbook.no-ending-arguments-by-text": "Do not end an argument by message — finish it out loud, or leave it open until we can.",
  "playbook.no-criticism-by-text": "Do not tell me what I have done wrong in a message; say it to my face.",
  "playbook.no-money-by-text": "Do not settle a decision about money in a message thread.",
  "playbook.no-reading-my-messages-after": "Do not read my private messages after I die, whatever else you decide to keep.",

  /* ── the instruction sheet ─────────────────────────────────────
     Seven headings, on the four channels the spec declares. Not the four
     sections: those are the order the questions are asked in, and a card is
     what somebody checks before they post, answer or put a phone down. Every
     body under these is the reader's own chosen words and nothing composed
     for them.

     Three of the twelve are restrictive multis, and a card prints a title and
     a body and nothing else — no prompt travels with the answer. So the title
     has to carry the direction that the option label cannot: "An apology that
     matters" is a thing that must never arrive as a message, and under a
     heading that did not say so it would read as the opposite. That is why
     `card.spoken` states the prohibition in full, and why the posting card is
     headed "before", which is true of a ceiling on a child's photograph and of
     a list of things that need asking first alike. */
  "card.answering": "How fast I answer, and when work reaches me",
  "card.together": "The phone when we are together",
  "card.photographs": "Intimate photographs",
  "card.posting": "Before anything is posted or repeated",
  "card.open": "What is open, and to whom",
  "card.afterwards": "What is left afterwards",
  "card.spoken": "What must never arrive as a message",

  /* ── the result page ───────────────────────────────────────────
     A label over the grounds, and two lists the weights make. The headings are
     statements about the reader's own numbers and never about what they have
     «allowed», «agreed to» or «decided» — three of the twelve answers are
     lists of things that may not happen, and a caption in the permissive
     direction would print them as their opposite. Nothing here says anything
     about phubbing, sharenting or digital legacy: the hedged version of what
     that research supports is in the sourceNote, which the result page already
     draws under this one. */
  "view.rests": "Rests on:",
  "view.heaviest.title": "What you weighted heaviest",
  "view.heaviest.note": "Eight or more out of ten. Nothing is added up and nothing is compared with anybody — this is where you said there is least give, which is what somebody needs to know before they walk into one of them.",
  "view.lightest.title": "What you weighted lightest",
  "view.lightest.note": "Three or less out of ten. That is not the same as having no position: it is you saying there is room to move here, and that is worth as much to the person reading this as the list above.",
};
