/**
 * boundaries — English, and the source of truth for the other three.
 *
 * Generated by scripts/bank-to-messages.mjs from docs/banks/boundaries.json, which
 * is where these sentences were written and critiqued. This file is that bank
 * keyed the way core/stance.ts looks words up, so a prompt has exactly one
 * home. test/i18n/stance-keys.test.ts fails if the two drift.
 *
 * Item bank © the author, all rights reserved. See LICENSE.
 */
export default {
  "title": "Boundaries",
  "tagline": "Twelve things about your door, your sleep and your money, each with the weight you put on it.",
  "framework": "Twelve stated positions — nothing scored, nobody assessed",
  "sourceNote": "There is no validated instrument behind this one and there could not be: what you would lend a brother, and how late is too late before you want a message, are not psychological constructs. They are facts about how you live. The word «boundary» reaches this page from two directions — family systems theory, where it describes where one part of a family stops and another begins, and a self-help literature that has produced no outcome study worth citing — so it is used here as an ordinary English word with nothing claimed for it. Nothing is scored, banded, or compared to anybody. One thing is worth saying plainly rather than in a footnote: everything you write here is either a statement about your own conduct or a request, and a request is something the other person is free to decline. That rule is why no question here asks you to set a rule over another adult — not who they may see, not who they may write to, not where they are. Where an answer describes an arrangement you did not agree to, this page records it as exactly that and does not call it a preference. And nothing on this page reads your answers for signs of anything.",

  /* ── the sections ─────────────────────────────────────────────────── */
  "section.home.title": "The door and the evening",
  "section.home.note": "Three things decided by whoever moves first: who arrives, who walks in, and how long you wait.",
  "section.people.title": "Everyone else in it",
  "section.people.note": "Exes, friends, family, and what any of them get told.",
  "section.body.title": "Your body and your sleep",
  "section.body.note": "Two things that are easier to say now than in the moment.",
  "section.yours.title": "Yours to give",
  "section.yours.note": "Your things, your money, your time — what leaves without a conversation first.",

  /* ── the questions ────────────────────────────────────────────────── */
  "stance.unannounced-visit.prompt": "Who can arrive at your home without telling you first?",
  "stance.closed-door.prompt": "What does a closed door in your home mean?",
  "stance.lateness.prompt": "How late can someone be before you expect a message?",
  "stance.partner-ex-friend.prompt": "A partner stays friends with an ex. What do you need?",
  "stance.own-ex-contact.prompt": "An ex sends you a message. What do you do?",
  "stance.friend-rude.prompt": "A friend is cruel about someone you love. What do you do?",
  "stance.told-outside.prompt": "Who gets to hear about an argument at home?",
  "stance.public-touch.prompt": "What touch in public is fine with you?",
  "stance.woken.prompt": "What is a good enough reason to wake you?",
  "stance.things-read.prompt": "Who can go through your things without asking?",
  "stance.money-family.prompt": "How much can you lend family without a conversation?",
  "stance.volunteered.prompt": "Someone commits you to something. What do you do?",

  /* ── what may be answered ─────────────────────────────────────────── */
  /* unannounced-visit */
  "stance.unannounced-visit.opt.nobody": "Nobody — they message first",
  "stance.unannounced-visit.opt.parent": "A parent can",
  "stance.unannounced-visit.opt.family": "Any close family can",
  "stance.unannounced-visit.opt.anyone": "Anyone close to me can",
  "stance.unannounced-visit.opt.notMine": "Not something I decide",
  "stance.unannounced-visit.opt.never": "It has never come up",
  /* closed-door */
  "stance.closed-door.opt.nobody": "Nobody comes in at all",
  "stance.closed-door.opt.knockWait": "Knock and wait for an answer",
  "stance.closed-door.opt.knockIn": "Knock and come straight in",
  "stance.closed-door.opt.openHouse": "Doors are not closed here",
  "stance.closed-door.opt.never": "It has never come up",
  /* lateness */
  "stance.lateness.opt.always": "Any lateness at all",
  "stance.lateness.opt.ten": "About ten minutes",
  "stance.lateness.opt.thirty": "About half an hour",
  "stance.lateness.opt.hour": "An hour or more",
  "stance.lateness.opt.never": "I never need a message",
  /* partner-ex-friend */
  "stance.partner-ex-friend.opt.nothing": "Nothing — it is theirs",
  "stance.partner-ex-friend.opt.toKnow": "Only to know it exists",
  "stance.partner-ex-friend.opt.told": "To be told before they meet",
  "stance.partner-ex-friend.opt.met": "To have met them myself",
  "stance.partner-ex-friend.opt.hard": "I find it hard either way",
  "stance.partner-ex-friend.opt.unknown": "I do not know yet",
  /* own-ex-contact */
  "stance.own-ex-contact.opt.sayFirst": "Say so at home before replying",
  "stance.own-ex-contact.opt.replyThenSay": "Reply, then mention it",
  "stance.own-ex-contact.opt.replyQuiet": "Reply and keep it to myself",
  "stance.own-ex-contact.opt.noReply": "I do not reply",
  "stance.own-ex-contact.opt.blocked": "They cannot reach me",
  "stance.own-ex-contact.opt.never": "It has not happened",
  /* friend-rude */
  "stance.friend-rude.opt.thereAndThen": "Say something there and then",
  "stance.friend-rude.opt.after": "Say something to them later",
  "stance.friend-rude.opt.tellThem": "Tell the person it was about",
  "stance.friend-rude.opt.nothing": "Nothing — I let it go",
  "stance.friend-rude.opt.distance": "See less of that friend",
  "stance.friend-rude.opt.notHappened": "It has not happened",
  /* told-outside */
  "stance.told-outside.opt.nobody": "Nobody outside the room",
  "stance.told-outside.opt.onePerson": "One person I trust",
  "stance.told-outside.opt.friends": "Close friends",
  "stance.told-outside.opt.family": "Family too",
  "stance.told-outside.opt.anyone": "I do not mind who",
  "stance.told-outside.opt.undecided": "I have not decided",
  /* public-touch */
  "stance.public-touch.opt.none": "Nothing at all",
  "stance.public-touch.opt.hand": "A hand or an arm",
  "stance.public-touch.opt.kiss": "A short kiss too",
  "stance.public-touch.opt.anything": "Anything I would do at home",
  "stance.public-touch.opt.depends": "It depends who is watching",
  /* woken */
  "stance.woken.opt.never": "Do not wake me for anything",
  "stance.woken.opt.emergency": "An emergency only",
  "stance.woken.opt.today": "Anything that changes today",
  "stance.woken.opt.anything": "Wake me for anything",
  "stance.woken.opt.depends": "It depends on the hour",
  /* things-read */
  "stance.things-read.opt.nobody": "Nobody goes through my things",
  "stance.things-read.opt.ask": "Anyone who asks first",
  "stance.things-read.opt.partner": "The person I live with",
  "stance.things-read.opt.notMine": "Not something I decide",
  "stance.things-read.opt.never": "It has never come up",
  /* money-family */
  "stance.money-family.opt.discussFirst": "Nothing without discussing it",
  "stance.money-family.opt.dayPay": "A day's pay",
  "stance.money-family.opt.weekPay": "A week's pay",
  "stance.money-family.opt.monthPay": "A month's pay",
  "stance.money-family.opt.whatever": "Whatever they needed",
  "stance.money-family.opt.neverLend": "I do not lend to family",
  /* volunteered */
  "stance.volunteered.opt.sayNo": "I say no on the spot",
  "stance.volunteered.opt.pullOut": "I get out of it later",
  "stance.volunteered.opt.sayLater": "I do it, then say so afterwards",
  "stance.volunteered.opt.doIt": "I do it and say nothing",
  "stance.volunteered.opt.notHappened": "It has not happened to me",

  /* ── the playbook ─────────────────────────────────────────────────── */
  /* this is fine */
  "playbook.ok.door.open": "Let yourself in if the door is open. You never have to ring first.",
  "playbook.ok.door.hour": "Message me an hour before you come over and the answer will almost always be yes.",
  "playbook.ok.doorclosed.knock": "Knock if my door is shut, then come straight in. I am not hiding from you.",
  "playbook.ok.late.relax": "Do not apologise for being ten minutes late. I genuinely had not noticed.",
  "playbook.ok.late.line": "If you are under half an hour late, do not bother texting. I will order for us.",
  "playbook.ok.ex.theirs": "See your ex as often as you like. I do not need a report on it afterwards.",
  "playbook.ok.myex.reply": "If my ex messages me I will reply. It is not a secret and it is not the start of anything.",
  "playbook.ok.myex.ask": "Ask me directly whether I have heard from my ex. You will get a straight answer, every time.",
  "playbook.ok.friend.push": "Push back in front of everyone if I say something unfair. I would rather have it out there.",
  "playbook.ok.told.talk": "Tell someone you trust when we have argued. I would rather that than you sitting on it.",
  "playbook.ok.touch.street": "Hold my hand in the street. Kiss me at the station. None of that embarrasses me.",
  "playbook.ok.wake.me": "Wake me if you need me. I would rather lose an hour of sleep than hear about it at breakfast.",
  "playbook.ok.things.open": "You can go through my things. I am not going to move anything first.",
  "playbook.ok.money.lend": "If your family needs money, lend it to them. Tell me afterwards rather than asking me first.",
  /* this is not */
  "playbook.no.door.message": "Do not turn up at my door without messaging first. Having a key is not an invitation.",
  "playbook.no.doorclosed.open": "Do not open my door without knocking. Wait for me to answer before you come in.",
  "playbook.no.late.silence": "Do not leave me standing there. If you are more than ten minutes away, send me one line.",
  "playbook.no.ex.afterwards": "Do not arrange to see your ex and tell me afterwards. Tell me beforehand instead.",
  "playbook.no.ex.pretend": "Do not ask me to be relaxed about this. I am not, and pretending otherwise would be worse.",
  "playbook.no.myex.number": "Do not pass my number to my ex, whatever reason they give you for wanting it.",
  "playbook.no.friend.jokes": "Do not make jokes about the people I love in front of others. Not even the good ones.",
  "playbook.no.told.story": "Do not repeat what I said in a fight to your family. Not even as a funny story at dinner.",
  "playbook.no.touch.colleagues": "Do not kiss me in front of your colleagues. A hand on my back is fine.",
  "playbook.no.touch.any": "Do not reach for me in public. It is not about you and it is not going to change.",
  "playbook.no.wake.morning": "Do not wake me to tell me something that will still be true in the morning.",
  "playbook.no.things.out": "Do not go through my things while I am out. Ask me and I will show you myself.",
  "playbook.no.money.promise": "Do not promise money to your family before you have said the number out loud to me.",
  "playbook.no-lend-then-tell": "Do not lend money to someone in your family and tell me about it afterwards.",
  "playbook.no.volunteer.yes": "Do not say yes on my behalf. Tell them you will check with me — I will usually say yes anyway.",

  /* ── the instruction sheet ─────────────────────────────────────
     Five headings, on the four channels the spec declares. Not the four
     sections: those are the order the questions are asked in, and a card is
     what somebody checks on the way through the door. Every body under these
     is the reader's own chosen words and nothing composed for them. */
  "card.arriving": "Before you come in",
  "card.committing": "What I can be committed to",
  "card.clock": "Lateness, and being woken",
  "card.touch": "Touch in public",
  "card.repeating": "Exes, and what gets repeated",

  /* ── the result page ───────────────────────────────────────────
     Two lists and the sentence over them. The headings are statements about
     the reader's own numbers — never about what they have «asked for» or
     «decided», because two of the twelve can be answered «Not something I
     decide» and the sourceNote promises those are recorded as exactly that. */
  "view.weightTitle": "Where the weight fell",
  "view.weightNote": "The weights you gave, read back at the two ends. Anything you put between four and seven is not missing — it is above, in the order you were asked.",
  "view.heaviestTitle": "What you weighted heaviest",
  "view.heaviestNote": "Eight or more out of ten. These are the ones where somebody guessing wrong costs the most.",
  "view.lightestTitle": "What you weighted lightest",
  "view.lightestNote": "Three or less out of ten. There is room to move here, which is not the same thing as not minding.",
};
